### ISSUE TITLE
kafka-junit support for kafka_2.13 (Kafka 2.6.0 recommends using Scala 2.13.x)

### ISSUE THREAD

**Issue by geirsandearm** [charithe/kafka-junit#58]
Seems that kafka-junit 4.1.0 works until Scala version 2.12.11. When scala-library is updated to 2.12.12  runtime errors occurs
Stacktrace:
java.lang.NoClassDefFoundError: scala/math/Ordering$$anon$7
        at kafka.api.ApiVersion$.orderingByVersion(ApiVersion.scala:45) ~[kafka_2.12-2.6.0.jar:?]
        at kafka.api.ApiVersion.compare(ApiVersion.scala:141) ~[kafka_2.12-2.6.0.jar:?]
        at kafka.api.ApiVersion.compare$(ApiVersion.scala:140) ~[kafka_2.12-2.6.0.jar:?]
        at kafka.api.KAFKA_2_6_IV0$.compare(ApiVersion.scala:348) ~[kafka_2.12-2.6.0.jar:?]
        at kafka.api.KAFKA_2_6_IV0$.compare(ApiVersion.scala:348) ~[kafka_2.12-2.6.0.jar:?]
        at scala.math.Ordered.$greater$eq(Ordered.scala:91) ~[scala-library-2.12.12.jar:?]
        at scala.math.Ordered.$greater$eq$(Ordered.scala:91) ~[scala-library-2.12.12.jar:?]
        at kafka.api.KAFKA_2_6_IV0$.$greater$eq(ApiVersion.scala:348) ~[kafka_2.12-2.6.0.jar:?]
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1564) ~[kafka_2.12-2.6.0.jar:?]
        at kafka.server.KafkaConfig.<init>(KafkaConfig.scala:1272) ~[kafka_2.12-2.6.0.jar:?]
        at com.github.charithe.kafka.EphemeralKafkaBroker.buildKafkaConfig(EphemeralKafkaBroker.java:229) ~[kafka-junit-4.1.10.jar:?]

**Comment by charithe** [comment]
I think this is an issue with Kafka itself. The version of Scala used with the Kafka_2.12 artifact is 2.12.11. This will most likely go away when they release the next version.

**Comment by geirsandearm** [comment]
@charithe How about providing kafka-junit support for kafka_2.13 artifact ?

**Comment by charithe** [comment]
Ah, sorry, I didn't read the title of the issue properly. I don't think there'll be a problem with switching to the 2.13 artifact. It might be troublesome for Scala projects but I am not aware of any that do use this library.
